apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-a
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-b
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
