apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: b-sink
  namespace: my-namespace
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "4"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/targetUtilizationPercentage: "30"
    spec:
      containers:
       - image: docker.io/aliok/b-sink
         env:
         - name: LATENCY
           value: "100"
