apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafkasource-a
  namespace: my-namespace
spec:
  consumerGroup: group-a
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - topic-a
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: a-processor
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafkasource-b
  namespace: my-namespace
spec:
  consumerGroup: group-b
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - topic-b
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: b-sink
